# Generated by Django 6.1.1 on 2026-09-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginfailure",
            name="username",
            field=models.CharField(
                blank=True,
                default="",
                help_text="As typed, in lowercase",
                max_length=150,
            ),
        ),
        migrations.CreateModel(
            name="RateLimitHit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scope", models.CharField(max_length=20)),
                ("key", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["scope", "key", "created_at"],
                        name="accounts_ra_scope_c2c060_idx",
                    )
                ],
            },
        ),
    ]
