# Generated by Django 6.1.1 on 2026-09-27 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("curriculum", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Attempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=200)),
                ("block_id", models.CharField(blank=True, max_length=100)),
                ("lesson_version", models.PositiveIntegerField(blank=True, null=True)),
                ("code", models.TextField()),
                ("passed", models.BooleanField(default=False)),
                ("goals", models.JSONField(default=list)),
                ("sim_version", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attempts",
                        to="curriculum.lesson",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "key"], name="progress_at_user_id_8ac389_idx"
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="progress_at_user_id_21f356_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CodeDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="lesson/<lesson>/<block> or playground/<challenge>",
                        max_length=200,
                    ),
                ),
                ("code", models.TextField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drafts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "key"), name="one_draft_per_editor"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LessonProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page",
                    models.PositiveIntegerField(
                        default=0, help_text="Furthest page reached (from 0)"
                    ),
                ),
                (
                    "done",
                    models.JSONField(
                        default=list, help_text="Ids of finished quizzes and challenges"
                    ),
                ),
                (
                    "finished",
                    models.BooleanField(
                        default=False, help_text="Reached the end of the lesson"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="curriculum.lesson",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "lesson progress",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "lesson"), name="one_progress_per_lesson"
                    )
                ],
            },
        ),
    ]
