# Generated by Django 6.1.1 on 2026-09-27 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="source",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="The file in content/ this lesson was imported from (empty if it was made in the admin).",
                max_length=200,
            ),
        ),
    ]
