# Generated by Django 6.1.1 on 2026-09-27 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="robot",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="The team's real robot (ports and wheel sizes), used when students copy code to Pybricks. Empty means it's built like the Trainer Bot. Coaches set it on the team page.",
            ),
        ),
    ]
