# Generated by Django 6.1.1 on 2026-09-28 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MissionGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("title", models.CharField(max_length=120)),
                ("summary", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("published", models.BooleanField(default=True)),
                (
                    "spec",
                    models.JSONField(
                        help_text="The game: field, models, missions, tiers, attachments, robot..."
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="The folder this game was imported from.",
                        max_length=300,
                    ),
                ),
            ],
            options={
                "ordering": ["order", "slug"],
            },
        ),
        migrations.CreateModel(
            name="MissionChallenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Used in the challenge's web address.", unique=True
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("tier", models.PositiveIntegerField(default=1)),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Challenges unlock one after another, in this order.",
                    ),
                ),
                ("published", models.BooleanField(default=True)),
                (
                    "spec",
                    models.JSONField(
                        help_text="The whole challenge: runs, models, goals, stars, starter, solution..."
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="The file this challenge was imported from.",
                        max_length=300,
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="challenges",
                        to="missions.missiongame",
                    ),
                ),
            ],
            options={
                "ordering": ["game", "order", "slug"],
            },
        ),
        migrations.CreateModel(
            name="MissionProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stars", models.PositiveSmallIntegerField(default=0)),
                ("best_score", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="missions.missionchallenge",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mission_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "mission progress",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "challenge"),
                        name="one_progress_per_mission_challenge",
                    )
                ],
            },
        ),
    ]
